_target_: src.models.vcc_lightning.VCCModule
net:
  _target_: src.models.components.vcc_model_attention.CellModelAttention
  ko_processor_args:
    input_size: 18080
    hidden_layers: [2048,1024,512]
    output_size: 128
    dropout: 0.0
    activation: relu
    # no_processing: true
  exp_processor_args:
    input_size: 18080
    hidden_layers: [2048,1024,512]
    output_size: 128
    dropout: 0.0
    activation: relu
    # no_processing: true
  attention_args:
    embed_dim: 128 # Must be same as the dimensions of you key and value if you choose so
    num_heads: 1
  decoder_args:
    input_size: 128
    hidden_layers: [256,512,1024,2048]
    output_size: ${model.net.exp_processor_args.input_size}
    dropout: 0.0
    activation: relu
lr: 1e-5
max_lr: 1e-2
weight_decay: 1e-5
composite_loss_lambda: 1
