
_target_: src.models.vcc_lightning.VCCModule
net:
  _target_: src.models.components.basic_vcc_model.CellModelFiLM
  ko_processor:
    _target_: src.models.components.basic_vcc_model.ProcessingNN
    input_size: 256
    hidden_size: 2048
    num_hidden_layers: 4
    output_size: 256
    dropout: 0.0
    activation: silu
  exp_processor:
    _target_: src.models.components.basic_vcc_model.ProcessingNN
    input_size: 18080
    hidden_size: 2048
    num_hidden_layers: 4
    output_size: 256
    dropout: 0.0
    activation: silu
  film_processor:
    _target_: src.models.components.basic_vcc_model.ProcessingNN
    input_size: 256
    hidden_size: 2048
    num_hidden_layers: 1
    output_size: 512 # Twice exp_processor output
    dropout: 0.0
    activation: silu
  decoder:
    _target_: src.models.components.basic_vcc_model.ProcessingNN
    input_size: 256
    hidden_size: 2048
    num_hidden_layers: 4
    output_size: ${model.net.exp_processor.input_size}
    dropout: 0.0
    activation: silu
loss_fn:
  _target_: src.models.components.loss_functions.CompositeLoss
  loss_functions:
    - _target_: src.models.components.loss_functions.SoftDiceLoss
      temperature: 1
      threshold: 0
    - _target_: src.models.components.loss_functions.DiffExpAwareMSELoss
      temperature: 0.75
      threshold: 1.5
      beta: 1
    - _target_: src.models.components.loss_functions.GenewiseMSELoss
    - _target_: src.models.components.loss_functions.DiffGeneBCELoss
      device: cuda:2
      pos_weight: 3
      temperature: 1
      threshold: 0
    # - _target_: src.models.components.loss_functions.PerturbationSimilarityLoss
    # - _target_: src.models.components.loss_functions.LaplacianRegularizerLoss
  weights:
    - 1
    - 1
    - 1
    - 1
    # - 1e-5
optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-5
  weight_decay: 1e-5
scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
  _partial_: true
  T_0: 5
  T_mult: 2
