
_target_: src.models.projectionvcc_lightning.VCCModule
net:
  _target_: src.models.components.basic_vcc_model.ProjectorCellModel
  ko_processor_args:
    input_size: 256
    hidden_layers: [512,512,512]
    output_size: 256
    dropout: 0.0
    activation: relu
    # no_processing: true
  exp_processor_args:
    input_size: 18080
    hidden_layers: [512,512,512]
    output_size: 256
    dropout: 0.0
    activation: relu
    # no_processing: true
  projector_args:
    input_size: 256
    hidden_layers: [256, 128]
    output_size: 64
    dropout: 0.0
    activation: relu
    residual_connection: false # Avoids negative values
    # no_processing: true
  decoder_args:
    input_size: ${model.net.projector_args.output_size}
    hidden_layers: [512, 1024, 2048, 4096]
    output_size: ${model.net.exp_processor_args.input_size}
    dropout: 0.0
    activation: relu
    residual_connection: false # Avoids negative values
  fusion_type: bilinear
primary_loss:
  _target_: src.models.components.loss_functions.CompositeLoss
  loss_functions:
    - _target_: src.models.components.loss_functions.DiffExpAwareMSELoss
      beta: 1
    - _target_: src.models.components.loss_functions.MyMSELoss
  weights:
    - 1
    - 0.2
contrastive_loss:
  _target_: src.models.components.loss_functions.WeightedContrastiveLoss
  alpha: 1
  temperature: 0.1
contrastive_weight: 30
optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-5
  weight_decay: 1e-5
scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
  _partial_: true
  T_0: 15
