# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    # -   id: check-added-large-files

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0 # Use the desired version
    hooks:
    -   id: check-added-large-files
        # args: ["--maxkb=2000"] # Optional: Set max file size in KB (default is 500KB)
        exclude: "\\.ipynb$" # Optional: Exclude specific files from the check

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.12.1
  hooks:
    # Run the linter.
    - id: ruff
      types_or: [ python, pyi ]
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi ]
# - repo: https://github.com/facebook/pyrefly
#   rev: 0.22.0
#   hooks:
#     - id: pyrefly-typecheck
- repo: https://github.com/PyCQA/isort
  rev: 6.0.1
  hooks:
    - id: isort
      args: ["--profile", "black", "--filter-files"]

- repo: https://github.com/econchick/interrogate
  rev: 1.7.0 # or master if you're bold
  hooks:
    - id: interrogate
      args:
          [
            --verbose,
            --fail-under=80,
            --ignore-init-module,
            --ignore-init-method,
            --ignore-module,
            --ignore-nested-functions,
            -vv,
          ]
   # jupyter notebook cell output clearing
- repo: https://github.com/kynan/nbstripout
  rev: 0.8.1
  hooks:
    - id: nbstripout

# jupyter notebook linting
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.9.1
  hooks:
    - id: nbqa-black
      args: ["--line-length=99"]
    - id: nbqa-isort
      args: ["--profile=black"]
    - id: nbqa-flake8
      args:
          [
            "--extend-ignore=E203,E402,E501,F401,F841",
            "--exclude=logs/*,data/*",
          ]
