[workspace]
authors = ["Rajeeva-IITM <bt20d204@smail.iitm.ac.in>"]
channels = ["conda-forge"]
name = "vcc"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
polars = ">=1.31.0,<2"
notebook = ">=7.4.4,<8"
pytorch-gpu = ">=2.7.1,<3"
transformers = ">=4.53.0,<5"
lightning = ">=2.5.2,<3"
seaborn = ">=0.13.2,<0.14"
rich = ">=14.0.0,<15"
hydra-core = ">=1.3.2,<2"
pre-commit = ">=4.2.0,<5"
anndata = ">=0.11.4,<0.12"
scikit-learn = ">=1.7.1,<2"
hvplot = ">=0.11.3,<0.12"
wandb = ">=0.21.0,<0.22"
numpy = ">=2.3.2,<3"
pip = ">=25.2,<26"
optuna = ">=4.4.0,<5"
optuna-integration = ">=4.4.0,<5"
torchmetrics = ">=1.8.1,<2"
pytorch_scatter = ">=2.1.2,<3"

[system-requirements]
cuda = "12.0"

[pypi-dependencies]
icecream = ">=2.1.5, <3"
rootutils = ">=1.0.7, <2"
optuna-dashboard = ">=0.19.0, <0.20"
