defaults:
  - data: dataset
  - model: model
  - trainer: trainer
  - callbacks: defaults
  - paths: defaults
  - logging: wandb
  # - hydra: defaults
  - _self_

seed: 42

logging:
  wandb:
    job_type: VCC

ckpt_path: null # In case one wants to resume training
compile: true
