defaults:
  - trainer: trainer
  - callbacks: callbacks_for_tuning
  - paths: defaults
  - data: dataset
  - model: model
  - _self_

savename: tuning_${now:%d_%m_%Y}


trainer:
  # logger: false
  enable_checkpointing: false
  # enable_progress_bar: false
  # enable_model_summary: false
  max_epochs: 50
  default_root_dir: ${paths.log_dir}${data.metadata.groupname}/

optuna:
  objective: val_auc_roc
  n_jobs: 1
  n_trials: 100
  direction: maximize

  sampler:
    _target_: optuna.samplers.TPESampler
    seed: 42

  storage:
    _target_: optuna.storages.JournalFileStorage
    file_path: ${paths.output_dir}/${data.metadata.groupname}.log
